/*
 * Copyright (C) 2014 UndeadScythes
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.undeadscythes.pgpmailchecker.mail;

import com.undeadscythes.ceremail.Mail;

/**
 *
 * @author UndeadScythes
 */
public class MailData extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    
    public MailData() {
        initComponents();
    }
    
    public void load(Mail mail) {
        if (mail == null) {
            conversationText.setText("");
            subjectText.setText("");
            contentText.setText("");
        } else {
            conversationText.setText(mail.getSenderName() + " -> " + mail.getRecipientName());
            subjectText.setText(mail.getSubject());
            contentText.setText(mail.getContent());
            contentText.setCaretPosition(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JScrollPane contentScroll = new javax.swing.JScrollPane();
        contentText = new javax.swing.JTextArea();
        javax.swing.JLabel conversationLabel = new javax.swing.JLabel();
        javax.swing.JLabel subjectLabel = new javax.swing.JLabel();
        conversationText = new javax.swing.JTextField();
        subjectText = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        contentText.setEditable(false);
        contentText.setColumns(20);
        contentText.setLineWrap(true);
        contentText.setRows(5);
        contentText.setWrapStyleWord(true);
        contentScroll.setViewportView(contentText);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.1;
        gridBagConstraints.weighty = 1.1;
        add(contentScroll, gridBagConstraints);

        conversationLabel.setText("Conversation:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(conversationLabel, gridBagConstraints);

        subjectLabel.setText("Subject:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(subjectLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(conversationText, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(subjectText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contentText;
    private javax.swing.JTextField conversationText;
    private javax.swing.JTextField subjectText;
    // End of variables declaration//GEN-END:variables
}
